# Compiler to use
CC = g++

# Compiler flags
CFLAGS = -Wall -std=c++11

# Name of the output file
OUTFILE = program

# Source files
SRC = SeqList.cpp test.cpp

all:
    $(CC) $(CFLAGS) $(SRC) -o $(OUTFILE)